/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-108207-g4ba68639ca-20220919"
#endif /* AVUTIL_FFVERSION_H */
